<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.6.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NPOI" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VDS.IDAL\VDS.IDAL.csproj" />
    <ProjectReference Include="..\VDS.Model\VDS.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="dnsDBUtil">
      <HintPath>..\Library\dnsDBUtil.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
