<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Configurations>Debug;Release;Release_Soulbrain;Release_UnEInternal;Release_Kakaowork;Release_Wonikqnc</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Soulbrain|AnyCPU'">
    <Optimize>false</Optimize>
    <DefineConstants>TRACE;Soulbrain</DefineConstants>
    <OutputPath>..\..\..\..\bin\common12\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Wonikqnc|AnyCPU'">
    <Optimize>false</Optimize>
    <DefineConstants>TRACE;Wonikqnc</DefineConstants>
    <OutputPath>..\..\..\..\bin\common12\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Kakaowork|AnyCPU'">
    <Optimize>false</Optimize>
    <DefineConstants>TRACE;Soulbrain</DefineConstants>
    <OutputPath>..\..\..\..\bin\common12\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_UnEInternal|AnyCPU'">
    <Optimize>false</Optimize>
    <DefineConstants>TRACE;UnEInternal</DefineConstants>
    <OutputPath>..\..\..\..\..\bin\common12\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\..\..\bin\common12\</OutputPath>
    <DefineConstants>TRACE;_UnEInternal _Soulbrain Wonikqnc</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Common.DAL\Common.DAL.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.IDAL\Common.IDAL.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Model\Common.Model.csproj" />
    <ProjectReference Include="..\..\..\SDMS\SDMS.DAL\SDMS.DAL.csproj" />
    <ProjectReference Include="..\..\..\SDMS\SDMS.IDAL\SDMS.IDAL.csproj" />
    <ProjectReference Include="..\..\..\SDMS\SDMS.Model\SDMS.Model.csproj" />
  </ItemGroup>

</Project>
