<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\SOP7\DNS\dnsBroadcast\dnsBroadcast\dnsBroadcast.csproj" />
  </ItemGroup>

</Project>