<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Configurations>Debug;Release;Release_Kakaowork</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>D:\UnESolution\bin\common12\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\..\bin\common12</OutputPath>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Kakaowork|AnyCPU'">
    <OutputPath>..\..\..\..\bin\common12</OutputPath>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DNS\dnsData\dnsData.csproj" />
    <ProjectReference Include="..\..\DNS\dnsSopID\dnsSopID.csproj" />
    <ProjectReference Include="..\SOPWebServer2\AgentFactory.BLL\AgentFactory.BLL.csproj" />
  </ItemGroup>

</Project>
