<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Configurations>Debug;Release;Release_Kakaowork</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\..\bin\common12</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Kakaowork|AnyCPU'">
    <OutputPath>C:\UnESolution\bin\common12\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>C:\UnESolution\bin\common12\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SDMS.Model\SDMS.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="dnsGeometry">
      <HintPath>..\..\..\..\bin\common12\netstandard2.0\dnsGeometry.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
