<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="EPPlus" Version="8.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\esdk\workspace\dnsGeometry\dnsGeometry\dnsGeometry.csproj" />
    <ProjectReference Include="..\..\Common\Common.IDAL\Common.IDAL.csproj" />
    <ProjectReference Include="..\..\Common\Common.Model\Common.Model.csproj" />
    <ProjectReference Include="..\..\DNS\dnsData\dnsData.csproj" />
    <ProjectReference Include="..\..\SDMS\SDMS.IDAL\SDMS.IDAL.csproj" />
    <ProjectReference Include="..\..\SDMS\SDMS.Model\SDMS.Model.csproj" />
    <ProjectReference Include="..\..\SOPManager\SOPManager.IDAL\SOPManager.IDAL.csproj" />
    <ProjectReference Include="..\..\SOPManager\SOPManager.Model\SOPManager.Model.csproj" />
    <ProjectReference Include="..\Hydrogen.IDAL\Hydrogen.IDAL.csproj" />
    <ProjectReference Include="..\Hydrogen.Model\Hydrogen.Model.csproj" />
  </ItemGroup>

</Project>
