<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\esdk\workspace\DNS_DBUtil\DNS_DBUtil\dnsDBUtil.csproj" />
    <ProjectReference Include="..\..\DNS\dnsData\dnsData.csproj" />
    <ProjectReference Include="..\..\SDMS\SDMS.Model\SDMS.Model.csproj" />
    <ProjectReference Include="..\Hynix.IDAL\Hynix.IDAL.csproj" />
    <ProjectReference Include="..\Hynix.Model\Hynix.Model.csproj" />
  </ItemGroup>

</Project>
