<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\..\bin\common12</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\esdk\workspace\DNS_DBUtil\DNS_DBUtil\dnsDBUtil.csproj" />
    <ProjectReference Include="..\..\SOPManager\SOPManager.Model\SOPManager.Model.csproj" />
    <ProjectReference Include="..\Dashboard.DAL\Dashboard.DAL.csproj" />
    <ProjectReference Include="..\Dashboard.IDAL\Dashboard.IDAL.csproj" />
    <ProjectReference Include="..\Dashboard.Model\Dashboard.Model.csproj" />
  </ItemGroup>

</Project>
